version: '3.1'
services:
  app:
    container_name: relexTestTask-app
    image: springboot-postgresql
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
  postgresql:
    container_name: relexTestTask-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=relexTestTask